
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjks?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: qwaszxedc
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.mysql.cj.jdbc.MysqlDataSource
#  mybatis.mapper-locations: classpath:mapper/*.xml
mybatis:
  mapper-locations: classpath:/mappers/*xml
  type-aliases-package: com.whjbatisgenerate.whj_batis_generate.dao